version: '2'
services:
  jenkins:
    build: .
    image: challisa/jenkins
    container_name: jenkins
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/jenkins_config'
      - '/var/run/docker.sock:/var/run/docker.sock'
    privileged: true
volumes:
  jenkins_data:
    driver: local
